install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host i686-pc-windows-msvc --profile minimal
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build: false
test_script:
  # We do not have libxcb and thus cannot build XCBConnection
  - cargo build --verbose --all-targets --no-default-features --features vendor-xcb-proto
  - cargo test --verbose --no-default-features --features vendor-xcb-proto
